export const CAPABILITY = {
  BASIC_DASHBOARD: "BASIC_DASHBOARD",
  RECOMMENDATIONS: "RECOMMENDATIONS",
  EVIDENCE_CAPTURE: "EVIDENCE_CAPTURE",
  API_ACCESS: "API_ACCESS",
} as const;

export type Capability = (typeof CAPABILITY)[keyof typeof CAPABILITY];

export const CAPABILITIES = Object.values(CAPABILITY);
